parti-renaissance/espace-militant

src/core/entities/PhoningCampaign.ts
src/core/entities/PhoningSession.ts
src/core/entities/PhoningSessionAdherent.ts
src/core/entities/PhoningSessionConfiguration.ts
src/data/PhoningCampaignRepository.ts
src/data/mapper/PhoningCampaignMapper.ts
src/data/mapper/PhoningSessionAdherentMapper.ts
src/data/mapper/PhoningSessionConfigurationMapper.ts
src/data/mapper/PhoningSessionMapper.ts
src/data/network/ApiService.ts
src/data/restObjects/RestPhoningCampaign.ts
src/data/restObjects/RestPhoningSession.ts
src/data/restObjects/RestPhoningSessionConfiguration.ts
src/data/restObjects/RestUserScope.ts

Phoning APIs

---

package.json
src/assets/localizables/fr.json
src/navigation/index.ts
src/screens/phoning/PhoningScreen.tsx
src/screens/phoningCampaignBrief/PhoningCampaignBriefNavigationData.ts
src/screens/phoningCampaignBrief/PhoningCampaignBriefScreen.tsx
yarn.lock

Phoning brief screen

---

src/assets/localizables/fr.json
src/core/entities/PhoningCampaign.ts
src/data/mapper/PhoningCampaignMapper.ts
src/data/restObjects/RestPhoningCampaign.ts
src/navigation/index.ts
src/navigation/screen.js
src/screens/phoning/PhoningNavigator.tsx
src/screens/phoning/PhoningScreen.tsx
src/screens/phoning/PhoningViewModelMapper.tsx
src/screens/phoning/campaign/PhoningCampaignRow.tsx
src/screens/phoningCampaignBrief/PhoningCampaignBriefScreen.tsx
src/screens/phoningCampaignScoreboard/PhoningCampaignScoreboardNavigationData.tsx
src/screens/phoningCampaignScoreboard/PhoningCampaignScoreboardScreen.tsx
src/screens/phoningCampaignScoreboard/PhoningScoreboardRowViewModelMapper.tsx
src/screens/shared/PhoningCampaignRankingView.tsx

Phoning campaign scoreboard

---

src/screens/home/retaliation/HomeRetaliationCard.tsx
src/screens/retaliation/RetaliationCard.tsx
src/screens/retaliation/RetaliationDetailScreen.tsx

Fix minor UI glitches for retaliation

---

src/assets/localizables/fr.json
src/core/entities/DoorToDoorPollConfig.ts
src/core/entities/PollExtraAnswer.ts
src/core/entities/PollExtraQuestion.ts
src/core/entities/StepType.ts
src/core/interactor/GetDoorToDoorCompletePollInteractor.ts
src/data/mapper/DoorToDoorPollConfigMapper.ts
src/data/mapper/PollConfigQuestionMapper.ts
src/data/restObjects/RestDoorToDoorPollConfig.ts
src/data/restObjects/RestPollConfigQuestion.ts
src/screens/doorToDoor/tunnel/TunnelDoorInterlocutorScreen.tsx
src/screens/doorToDoor/tunnel/qualification/QualificationDescription.tsx
src/screens/doorToDoor/tunnel/qualification/QualificationFormUserData.tsx
src/screens/doorToDoor/tunnel/qualification/QualificationFormUserDataViewModel.ts
src/screens/doorToDoor/tunnel/survey/DoorToDoorPollDetailScreenLoaded.tsx
src/screens/doorToDoor/tunnel/survey/DoorToDoorQuestionResult.ts
src/screens/doorToDoor/tunnel/survey/TunnelDoorPollScreen.tsx
src/screens/doorToDoor/tunnel/survey/mapper/PollExtraQuestionMapper.ts
src/screens/doorToDoor/tunnel/survey/providers/DoorToDoorQualificationComponentProvider.tsx
src/screens/pollDetail/PollDetailNavigationButtons.tsx
src/screens/pollDetail/PollDetailProgressBarViewModelMapper.ts
src/screens/pollDetail/PollDetailQuestionChoice.tsx
src/screens/pollDetail/PollDetailQuestionChoiceViewModel.ts
src/screens/pollDetail/QuestionChoiceRow.tsx
src/screens/pollDetail/QuestionChoiceRowViewModel.ts
src/screens/pollDetail/providers/PollDetailUserInformationsComponentProvider.tsx
src/screens/pollDetailUserData/PollDetailQuestionUserDataViewModel.ts

- Retrieve qualification questions from server
- Display qualification questions at the end of the survey
https://user-images.githubusercontent.com/24422094/146895314-99abb9b5-3964-424e-8722-db5297d8816e.mp4

Door to door qualification screen

---

src/assets/localizables/fr.json
src/core/interactor/SendDoorPollAnswersInteractor.ts
src/data/DoorToDoorRepository.ts
src/screens/doorToDoor/tunnel/doorSelection/TunnelDoorSelectionScreen.tsx
src/screens/doorToDoor/tunnel/interlocutor/TunnelDoorInterlocutorScreen.tsx
src/screens/doorToDoor/tunnel/survey/DoorToDoorPollDetailScreenLoaded.tsx

https://user-images.githubusercontent.com/24422094/148248488-77706035-551d-4684-b0c5-6652e9c9ccfa.mp4

PaP send interlocutor status & close floor

---

src/data/ActionsRepository.ts
src/navigation/screen.js
src/screens/actions/ActionsNavigator.tsx
src/screens/buildingDetail/BuildingDetailScreen.tsx
src/screens/doorToDoor/DoorToDoorNavigator.tsx
src/screens/doorToDoor/DoorToDoorScreen.tsx
src/screens/phoning/PhoningNavigator.tsx
src/screens/phoning/PhoningScreen.tsx
src/screens/polls/PollsNavigator.tsx

https://user-images.githubusercontent.com/24422094/148388477-a0026fe7-6a83-4760-a7cf-b2a9682925a9.mp4
https://user-images.githubusercontent.com/24422094/148390293-c7f4b754-fbbf-44b5-9900-dab7e07c68af.mp4

Fix nested navigation

---

src/assets/localizables/fr.json
src/core/entities/BuildingBlock.ts
src/core/interactor/GetDoorToDoorAddressesInteractor.ts
src/data/DoorToDoorRepository.ts
src/data/network/ApiService.ts
src/data/restObjects/RestBuildingEventRequest.ts
src/data/restObjects/RestBuildingTypeRequest.ts
src/screens/buildingDetail/BuildingDetailScreen.tsx
src/screens/buildingDetail/BuildingDetailScreenViewModelMapper.ts
src/screens/buildingDetail/BuildingLayoutBlockCardView.tsx
src/screens/buildingDetail/BuildingLayoutView.tsx
src/screens/buildingDetail/BuildingLayoutViewModelMapper.ts
src/screens/buildingDetail/BuildingStatusViewModelMapper.ts
src/screens/doorToDoor/DoorToDoorScreen.tsx
src/screens/doorToDoor/PoiAddressCardViewModelMapper.ts
src/screens/doorToDoor/tunnel/brief/DoorToDoorBriefScreen.tsx
src/screens/shared/AlertUtils.ts

- Modify building type
- Open/close Address
- Add/Remove floors business rules
- Caching data before PaP tunnel
- Add alerts before critical building actions (open/close building block, floors)
https://user-images.githubusercontent.com/24422094/148533629-baf9dfc7-c3fd-4cb1-bab2-d287e816524b.mp4
https://user-images.githubusercontent.com/24422094/148534049-a4857e66-1bc0-4325-bda6-d019c20f02ce.mp4

Building details finishes and fixes

---

src/screens/authentication/SignUpScreen.tsx
src/screens/personalInformation/BirthdayPicker.tsx
src/screens/personalInformation/LocationPicker.tsx
src/styles/colors.ts

https://user-images.githubusercontent.com/24422094/150518318-85cb36c4-88d5-4227-a451-9cf946e53606.mp4

Fix majority login

---

src/screens/authentication/ForgottenPasswordScreen.tsx
src/screens/authentication/SignUpScreen.tsx
src/screens/personalInformation/GenderPicker.tsx
src/screens/personalInformation/PhoneNumberInput.tsx

https://user-images.githubusercontent.com/24422094/150540421-416d1cdd-a694-4cd8-9262-e0d4959e4fc0.mp4

Majority login gender, phone & forgot password

---

src/navigation/index.ts
src/screens/buildingDetail/BuildingDetailScreen.tsx
src/screens/buildingDetail/BuildingVisitsHistoryView.tsx
src/screens/buildingDetail/KeyValueCell.tsx
src/screens/buildingDetail/KeyValueListView.tsx
src/screens/home/HomeNavigator.tsx
src/screens/home/HomeScreen.tsx

https://user-images.githubusercontent.com/24422094/151011660-ed6a8be9-785d-4108-aa2e-d69bca12d0c0.mp4

Fix door to door comments part 6

---

src/assets/localizables/fr.json
src/core/entities/DoorToDoor.ts
src/core/interactor/GetDoorToDoorAddressesInteractor.ts
src/data/mapper/DoorToDoorMapper.ts
src/data/restObjects/RestDoorToDoorAddress.ts
src/screens/buildingDetail/BuildingDetailScreen.tsx
src/screens/buildingDetail/BuildingDetailScreenViewModelMapper.ts
src/screens/buildingDetail/BuildingLayoutBlockCardView.tsx
src/screens/buildingDetail/BuildingLayoutView.tsx
src/screens/buildingDetail/BuildingLayoutViewModelMapper.ts
src/screens/buildingDetail/BuildingStatusViewModelMapper.ts
src/screens/doorToDoor/DoorToDoorCampaignCard.tsx
src/screens/doorToDoor/DoorToDoorCampaignCardViewModelMapper.ts
src/screens/doorToDoor/DoorToDoorMapView.tsx
src/screens/doorToDoor/DoorToDoorScreen.tsx
src/screens/doorToDoor/PoiAddressCard.tsx
src/screens/doorToDoor/PoiAddressCardViewModel.ts
src/screens/doorToDoor/PoiAddressCardViewModelMapper.ts
src/screens/personalInformation/PersonalInformationScreen.tsx
src/utils/DateFormatter.ts

https://user-images.githubusercontent.com/24422094/151396765-d99df24a-7b73-4101-a844-649a5df0f1b2.mp4

Fix minor bugs

---

src/assets/localizables/fr.json
src/core/entities/Tool.ts
src/core/interactor/GetHomeResourcesInteractor.ts
src/data/ToolsRepository.ts
src/data/mapper/RestToolMapper.ts
src/data/network/ApiService.ts
src/data/restObjects/RestToolsResponse.ts
src/screens/home/tools/HomeToolRowViewModel.ts
src/screens/pollDetail/PollDetailTools.tsx
src/screens/tools/ToolRow.tsx
src/screens/tools/ToolRowViewModel.tsx
src/screens/tools/ToolRowViewModelMapper.ts
src/screens/tools/ToolsContentViewModel.ts
src/screens/tools/ToolsContentViewModelMapper.ts
src/screens/tools/ToolsScreen.tsx

https://user-images.githubusercontent.com/24422094/151818171-615337b0-b63c-4603-ade4-a9f6c39415eb.mp4
https://user-images.githubusercontent.com/24422094/151818200-f66381b5-df14-4d1c-98d0-267e1a8d251b.mp4

Use remote tools

---

src/data/mapper/TimelineFeedItemMapper.ts

Keeps only critical issues to avoid noise

Remove sentry warnings

---

package.json
src/navigation/locationPickerModal/LocationPickerModalNavigatorParamList.ts
src/screens/locationPicker/LocationPickerScreen.tsx
src/screens/personalInformation/usePersonalInformationScreenContent.hook.ts
src/screens/signUp/SignUpScreen.tsx
src/utils/i18n.ts
yarn.lock

[fix: use event instead of params for callback]
[fix: i18n plurals]

Fix/pre release 3.9.1

---

src/components/EventRegisterForm/EventRegisterForm.tsx
src/components/ProfileCards/BotBilanCTA/BotBilanCTA.tsx
src/components/ProfileCards/ProcurationCTA/ProcurationCTA.tsx
src/helpers/homeFeed.ts

Modification suite à demande de Victor,
le browser expo utilise la petite popup au lieu d'ouvrir dans un nouvel onglet / nav externe

feature(RE-1739): use linking instead of windowed browser

---

app.json
app/_layout.tsx
package.json
src/hooks/useAppUpdate.tsx
src/screens/update/updateScreen.tsx
yarn.lock

expo update cause a crash on release. 
Temporaly remove it

fix: remove expo-update, crash on Release

---

src/screens/editPersonalInformation/personalInformations.tsx

Be aware that this PR is huuuuuuuuuge and need a conscientious review with loooooooooot of coffee 😅

RE-1892 disconnect

---

firebase.json

Reverts parti-renaissance/espace-militant#943

Revert "fix: .well-known files ignored by firebase"

---

app/_layout.tsx
src/config/firebaseConfig.web.ts
src/features/push-notification/hook/useInitPushNotification.ts
src/features/push-notification/logic/initRootAppNotification.ts
web/index.html

…er in private mode or embedded.

fix(private-browsing): fix white page on private browsing or embedded browser

---

src/components/Header/Header.tsx

Correction pour Victor le sniper ^^

fix(layout): RE-3364 incorrect header size / artifact on mobile web

---

src/components/ModalOrBottomSheet/ModalOrBottomSheet.tsx
src/features/profil/pages/referrals/components/ReferralFormModal.tsx
src/hooks/useKeyboardHeight.tsx

Corrigé sur iOS, en revanche impossible de trouver pourquoi il y a un ajout énorme de padding bottom sur mobile web, je pense que c'est lié à tamagui mais je ne comprends pas pourquoi.

fix(layout): RE-3383 modal layout

---

src/features/push-notification/api.ts
src/features/push-notification/hook/useInitPushNotification.ts
src/features/push-notification/schema.ts
src/hooks/notifications/useCheckNotificationsState.web.tsx
src/utils/isWebKit.ts

fix(notification): RE-3420 specific notification request for WebKit

---

src/components/DeleteAccountModal/Components/DeleteAccountModalStep1.tsx
src/components/DeleteAccountModal/Components/DeleteAccountModalStep2.tsx
src/components/DeleteAccountModal/DeleteAccountModal.tsx
src/features/profil/pages/dashboard/index.tsx

fix(deletion): RE-3461 deletaion wording
